### ISSUE TITLE
fix Feedback P2 Tests

### ISSUE THREAD

**Issue by anna-sara-maria** [anna-sara-maria/fundamentals-CI-integration#21]
**Instructions:**
Property (core CI feature #2 - testing): the CI server supports executing the automated tests of the group project. Testing is triggered as webhook, on the branch where the change has been made, as specified in the HTTP payload.Preparation: the students prepare a specific branch called "assessment" (not "master"). The students document in the README how test execution has been implemented and unit-tested.Assessment: The grader changes the oracle of an assertion in one test, and observes that tests are executed and at least one fails (the one with the changed assertion). Optionally, the grader has a look at the implementation or the tests of this feature.

**Feedback:** P2: create tests

**Comment by Adrelix** [comment]
assessment tests
